---
- name: Gather combined cert data
  set_fact:
    __ssl_combined_cert: "{{ lookup('file', ssl_certificate_source_path + '/' + ssl_certificate_name + '/server.crt') }}"
    __ssl_combined_ca: "{{ lookup('file', ssl_certificate_source_path + '/' + ssl_certificate_name + '/ca.crt', errors='ignore') | default(false) }}"
  tags:
    - update-ssl

- name: Create combined cert
  when: __ssl_combined_ca != False and __ssl_combined_ca|length > 0
  copy:
    content: |
      {{ __ssl_combined_cert }}
      {{ __ssl_combined_ca }}
    dest: "{{ ssl_certificate_path }}/{{ ssl_certificate_name }}/{{ ssl_certificate_name }}-full.pem"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: "{{ ssl_certificate_mode }}"
  tags:
    - update-ssl