---
- name: Create fullchain cert
  ansible.builtin.copy:
    content: "{{ [ssl_certificate_cert_content, ssl_certificate_ca_content] | select('truthy') | join('\n') }}\n"
    dest: "{{ ssl_certificate_path_cert }}/{{ ssl_certificate_name }}-full.pem"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: "{{ ssl_certificate_mode }}"
  notify: "{{ ssl_certificate_notify | default([]) }}"
  tags:
    - update-ssl
