---
- name: Gather combined cert data
  ansible.builtin.set_fact:
    __ssl_combined_cert: "{{ lookup('file', ssl_certificate_source_cert_path + ssl_certificate_source_cert_file) }}"
    __ssl_combined_ca: "{{ lookup('file', ssl_certificate_source_cert_path + ssl_certificate_source_ca_file, errors='ignore') | default('') }}"
  tags:
    - update-ssl

- name: Create combined cert
  ansible.builtin.copy:
    content: |
      {{ __ssl_combined_cert }}
      {{ __ssl_combined_ca }}
    dest: "{{ ssl_certificate_path_cert }}/{{ ssl_certificate_name }}-full.pem"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: "{{ ssl_certificate_mode }}"
  tags:
    - update-ssl
