---
- name: Ensure SSL certificate root directory exists
  ansible.builtin.file:
    dest: "{{ ssl_certificate_path }}"
    state: directory
    owner: "{{ ssl_certificate_path_owner }}"
    group: "{{ ssl_certificate_path_group }}"
    mode:  "{{ ssl_certificate_path_mode }}"

- name: Ensure SSL Certificate directory exists
  ansible.builtin.file:
    dest: "{{ ssl_certificate_path }}/{{ ssl_certificate_name }}"
    state: directory
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: "{{ ssl_certificate_path_mode }}"

- name: Install SSL certificate
  ansible.builtin.copy:
    src: "{{ __certificate.src }}"
    dest: "{{ ssl_certificate_path }}/{{ ssl_certificate_name }}/{{ __certificate.dest }}"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: "{{ ssl_certificate_mode }}"
  loop_control:
    loop_var: __certificate
  with_available_file_from_items:
    items: "{{ ssl_certificate_files }}"
    name: "{{ ssl_certificate_source_path }}/{{ ssl_certificate_name }}/{{ '{{' }} item.file {{ '}}' }}"
    key: src
  tags:
    - update-ssl

- name: Create combined cert
  ansible.builtin.include_tasks: combine_cert.yml
  when:
    - ssl_certificate_create_fullchain is defined
    - ssl_certificate_create_fullchain | bool
  tags:
    - update-ssl
