---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint molecule/default/converge.yml
  ansible-lint molecule/default/converge.yml
platforms:
  - name: "ssl-cert-${image:-ubuntu}-${tag:-jammy}"
    image: "${image:-ubuntu}:${tag:-jammy}"
provisioner:
  name: ansible
  log: False
scenario:
  name: default
verifier:
  name: ansible
