---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint molecule/default/converge.yml
  ansible-lint molecule/default/converge.yml
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: yes
scenario:
  name: default
verifier:
  name: ansible
