---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    # converge #1
    - name: 1 | check if /etc/ssl/private/kakaw/kakaw.key exists
      ansible.builtin.stat:
        path: /etc/ssl/private/kakaw/kakaw.key
      register: __file
      failed_when: not __file.stat.exists

    # converge #2 (alternate paths)
    - name: 2 | check if /alt/circle/circle.key exists
      ansible.builtin.stat:
        path: /alt/circle/circle.key
      register: __file
      failed_when: not __file.stat.exists

    # converge #3 (combined generation with a ca file)
    - name: 3 | check if combined cert was created
      ansible.builtin.slurp:
        src: /etc/ssl/private/combined/combined-full.pem
      register: __file_data
      failed_when: __file_data.content != 'Y2VydApjYQo='

    # converge #4 (combined generation without a ca file)
    - name: 4 | check if combined cert was created for kakaw
      ansible.builtin.slurp:
        src: /etc/ssl/private/kakaw/kakaw-full.pem
      register: __file_data
      failed_when: __file_data.content != 'Y2VydAo='

    # converge #5 (combined generation without a ca file & alt names/paths)
    - name: 5 | check if /alt/square/square.key exists
      ansible.builtin.stat:
        path: /alt/square/square.key
      register: __file
      failed_when: not __file.stat.exists

    - name: 5 | check if combined cert was created for alt/square
      ansible.builtin.slurp:
        src: /alt/square/square-full.pem
      register: __file_data
      failed_when: __file_data.content != 'Y2VydAo='

    - name: 6 | check custom full path was used
      ansible.builtin.stat:
        path: /etc/custom_cert/kakaw.key
      register: __full_path
      failed_when: not __full_path.stat.exists
